// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+@pinia+nuxt@0.4.11_typescript@5.2.2/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.7.0_ziueobtllsm7736rb35a7imot4/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.7.0_ziueobtllsm7736rb35a7imot4/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.7.0_ziueobtllsm7736rb35a7imot4/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.7.0_ziueobtllsm7736rb35a7imot4/node_modules/nuxt/dist/pages/runtime/plugins/router").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.7.0_ziueobtllsm7736rb35a7imot4/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+@nuxt+devtools@0.6.7_nuxt@3.7.0/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+@nuxt+devtools@0.6.7_nuxt@3.7.0/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+@nuxt+content@2.8.2/node_modules/@nuxt/content/dist/runtime/plugins/ws").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+@nuxt+content@2.8.2/node_modules/@nuxt/content/dist/runtime/legacy/plugins/documentDriven").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+@nuxtjs+color-mode@3.3.0/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+@nuxtjs+color-mode@3.3.0/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.7.0_ziueobtllsm7736rb35a7imot4/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../../plugins/awesome").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
